
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD AP DIV FP MULT NUMBER SUBoperacao : calcoperacao : operacao ADD calcoperacao : operacao SUB calccalc : expressaocalc : calc DIV expressaocalc : calc MULT expressaoexpressao : NUMBERexpressao : AP operacao FP'
    
_lr_action_items = {'NUMBER':([0,5,6,7,8,9,],[4,4,4,4,4,4,]),'AP':([0,5,6,7,8,9,],[5,5,5,5,5,5,]),'$end':([1,2,3,4,11,12,13,14,15,],[0,-1,-4,-7,-2,-3,-5,-6,-8,]),'ADD':([1,2,3,4,10,11,12,13,14,15,],[6,-1,-4,-7,6,-2,-3,-5,-6,-8,]),'SUB':([1,2,3,4,10,11,12,13,14,15,],[7,-1,-4,-7,7,-2,-3,-5,-6,-8,]),'FP':([2,3,4,10,11,12,13,14,15,],[-1,-4,-7,15,-2,-3,-5,-6,-8,]),'DIV':([2,3,4,11,12,13,14,15,],[8,-4,-7,8,8,-5,-6,-8,]),'MULT':([2,3,4,11,12,13,14,15,],[9,-4,-7,9,9,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'operacao':([0,5,],[1,10,]),'calc':([0,5,6,7,],[2,2,11,12,]),'expressao':([0,5,6,7,8,9,],[3,3,3,3,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> operacao","S'",1,None,None,None),
  ('operacao -> calc','operacao',1,'p_operacao_1','calc_yacc.py',6),
  ('operacao -> operacao ADD calc','operacao',3,'p_operacao_2','calc_yacc.py',10),
  ('operacao -> operacao SUB calc','operacao',3,'p_operacao_3','calc_yacc.py',14),
  ('calc -> expressao','calc',1,'p_calc_1','calc_yacc.py',18),
  ('calc -> calc DIV expressao','calc',3,'p_calc_2','calc_yacc.py',22),
  ('calc -> calc MULT expressao','calc',3,'p_calc_3','calc_yacc.py',26),
  ('expressao -> NUMBER','expressao',1,'p_expressao_1','calc_yacc.py',30),
  ('expressao -> AP operacao FP','expressao',3,'p_expressao','calc_yacc.py',34),
]
